# This is the setup file for twitter-archiver.

username: YOUR_TWITTER_USERNAME
password: YOUR_TWITTER_PASSWORD

# The name of the database file. You can name it
# whatever you want.
database: tweets.db

# This value is how many tweets do you want to save
# in the first run. Twitter don't let you to access
# every tweets you have. If this value is too big
# (such as 1000), the program will crash. '700' is
# a safe value.
init_save_amount: 700

# This value is how many tweets do you want to obtain
# when you update the database. Getting tweets costs
# time, so if you haven't post many tweets since the
# last time you update your database, it's better to
# keep this value as small as possible.
increment_amout: 300
